# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: STARMAN
email: dongli.init@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  STARMAN is a cross-platform package manager written in Ruby. It provides
  precompiled packages for different OS (e.g., Ubuntu, Mac OS X), and unified
  interfaces to use them.
baseurl: ''
github_username:  dongli
timezone: Asia/Shanghai

# Build settings
markdown: kramdown
